#!/bin/bash
edp=$(xrandr | grep -w connected | awk '{print $1}' | grep eDP | tr -d '\n')
hdmi=$(xrandr | grep -w connected | awk '{print $1}' | grep HDMI | tr -d '\n')
if [[ ! -z "$hdmi" ]];then
	xrandr --output "$hdmi" --rate 144.00 --mode 1920x1080 --left-of "$edp" --output "$edp" --rate 144.00 --mode 1920x1080
else
	xrandr --output "$edp" --rate 144.00 --mode 1920x1080
fi
~/.cache/redpaper/wallpaper.sh
	
	

