#!/bin/sh

#LAUNCHERS
#bspc config external_rules_command ~/.config/bspwm/scripts/external_rules_command
#BSPWM configuration
bspc config border_radius        20
bspc config border_width         2
bspc config window_gap           5
bspc config top_padding          5
bspc config bottom_padding       2
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       true
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  false
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config ignore_ewmh_struts false
bspc config honor_size_hints false
bspc config merge_overlapping_monitors false
bspc config focused_border_color	#e038c9
bspc monitor eDP1 -d 1 2 3 4 5 6 7 8 9 0
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9 0


#Floating applications
bspc rule -a java-lang-Thread state=floating desktop='^5'
bspc rule -a Arandr state=floating
bspc rule -a mpv state=tiling sticky=off
bspc rule -a Galculator state=floating
bspc rule -a Oblogout state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a Yad state=floating
bspc rule -a yad-calender=floating
bspc rule -a Carousel.py state=floating
bspc rule -a persepolis state=floating
bspc rule -a bluetooth state=floating
bspc rule -a Glade-previewer state=floating
bspc rule -a emacs state=tiling
bspc rule -a "Olivia - Video Option" state=floating -z bottom 200 right 200
bspc rule -a polybar private
bspc rule -a "Network Connections" state=floating

#open applications on specific workspaces
bspc rule -a firefox desktop='^1'
bspc rule -a steam desktop='4'
bspc rule -a Thunderbird  desktop='^10'
bspc rule -a "Tauon Music Box" desktop='^9'
bspc rule -a "Spotify" destkop='^9'
$HOME/.config/bspwm/autostart.sh
#polybar hidden when fullscreen for vlc, youtube, mpv ...
#find out the name of your monitor with xrandr
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_DP-1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI1)
#xdo below -t $(xdo id -n root) $(xdo id -a polybar-main_HDMI2)

###External rules
##Pseudo automatic mode: always splits focused window when opening new window
#bspc config external_rules_command ~/.config/bspwm/scripts/pseudo_automatic_mode
##Adjust new window: splits biggest windows to keep windows about the same size
#bspc config external_rules_command ~/.config/bspwm/scripts/adjust-new-window
