#!/bin/sh

#LAUNCHERS
#BSPWM configuration
bspc config border_radius        20
bspc config border_width         2
bspc config window_gap           5
bspc config left_padding         2
bspc config right_padding        2
bspc config single_monocle       true
bspc config click_to_focus       true
bspc config split_ratio          0.50
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focus_by_distance    true
bspc config focus_follows_pointer true
bspc config history_aware_focus  true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config ignore_ewmh_struts false
bspc config honor_size_hints false
bspc config merge_overlapping_monitors false
bspc config focused_border_color "#E5C07B"

#Floating applications

bspc rule -a Dialect state=floating
bspc rule -a crx_nngceckbapebfimnlniiiahkandclblb state=floating
bspc rule -a file-roller state=floating
bspc rule -a Arandr state=floating
bspc rule -a Gnome-disks state=floating
bspc rule -a yad-calender=floating
bspc rule -a Carousel.py state=floating
bspc rule -a bluetooth state=floating
bspc rule -a polybar private
bspc rule -a "Network Connections" state=floating

#open applications on specific workspaces
bspc rule -a Thunderbird  desktop='^10'
bspc rule -a "Tauon Music Box" desktop='^9' focus='on'
$HOME/.config/bspwm/autostart.sh
