#!/bin/sh
power
    echo 'power'
super + colon
    $HOME/.virtualenvs/yat/bin/python $HOME/Projects/yat/src/gui.py

super + semicolon
    dialect

super + r
    mpv $(xclip -o) || notify-send   "Mpv" "Invlid Url"
super + g
    mpv --no-resume-playback --shuffle ~/Videos/Music\ Videos 

super + shift + g
    $HOME/Carousel/scripts/wireguard-vpn -t

ctrl + q
    echo "firefox"

alt + space
    sh $HOME/.bin/finder

alt + shift + space
    sh $HOME/.bin/vp-finder

super + q 
    $HOME/.config/rofi/powermenu/powermenu.sh 

super + Tab
    bspc node -f next.local.\!hidden.window

super + shift + Tab
    bspc node -f prev.local.\!hidden.window

super + shift + y
    polybar-msg cmd toggle

super + y
    $HOME/.config/polybar/launch.sh

super + space
    $HOME/.config/rofi/launchers/colorful/launcher.sh

ctrl + space
	rofi -show run -disable-history -1

super + d
	redpaper -d

super + c
	redpaper -c

super + shift + c
	redpaper -b

super + shift + x
	bspc  node -k

super + b
	WINIT_X11_SCALE_FACTOR=1.1 alacritty  -e nvim $HOME/.config/bspwm/bspwmrc

super+shift+b
	WINIT_X11_SCALE_FACTOR=1.1 alacritty  -e nvim $HOME/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd && sxhkd

super + w
	bspc node -g {sticky=on, sticky=off}

super + p
    sh ~/.bin/cpicker -h

super + shift + p
    sh ~/.bin/cpicker -r

super + e
    caja

super + f
	bspc node --state \~fullscreen


super + shift + Escape
    xkill

#Terminal emulator
super + Return
	WINIT_X11_SCALE_FACTOR=1.2 alacritty

super + t
    WINIT_X11_SCALE_FACTOR=1.2 alacritty -e tomb -q open $HOME/Desktop/lollypop -k $HOME/Desktop/popen

super + shift + t
	tomb close

super + shift + d
	dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'
    xlayoutdisplay -p eDP1 -o HDMI1 -d 100

super + F5
    bspc wm --restart

super + shift + s
	pkill -x sxhkd && sxhkd

super + shift + q
	bspc node -c

super + shift + x
    bspc quit


#########################
# CONTROL + ALT KEYS    #
#########################


#firefox
ctrl + alt + f
    firefox

ctrl + shift + alt + p
    firefox --private-window

#Compton Toggle
ctrl + alt + o
     ~/.config/bspwm/scripts/compton-toggle.sh

ctrl + alt + Delete
    kill -9 -1


#########################
#     SCREENSHOTS       #
#########################

Print
	flameshot screen -r -c -p $HOME/Pictures/screenshots

shift + Print
	flameshot gui

#########################
#     MULTIMEDIA KEYS   #
#########################

#Raises volume
XF86AudioRaiseVolume
    amixer set Master 5%+

#Lowers volume
XF86AudioLowerVolume
    amixer set Master 5%-

#Mute
XF86AudioMute
    amixer -D pulse set Master 1+ toggle

XF86AudioPlay
    playerctl play-pause

XF86AudioNext
	playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86MonBrightnessUp
    xbacklight -inc 5

XF86MonBrightnessDown
    xbacklight -dec 5


super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

super + shift + {1-9,0}
    id=$(bspc query -N -n); bspc node -d ^{1-9,10}; bspc node -f ${id}}

super + v
	minimizer layout

super + {h,j,k,l}
    bspc node --focus {west,south,north,east}
    
super + shift + {h,j,k,l} 
    { dir=west \
    , dir=south \
    , dir=north \
    , dir=east  \
    }; \
    if bspc query -n $dir.window -N; then \
        bspc node --swap $dir --focus;\
    else \
        bspc node -m $dir --focus;\
    fi

super + {_,shift + }a
	bspc node @/ --flip {vertical,horizontal}

super + alt + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

super + {_,shift} + o
    bspc node @/ --rotate {90, 270}

super + r
    ~/.bin/open_in_mpv

super + {_,shift} + bracket{left}
    copyq {menu,show} clipboard
	
super + bracket{right}
    copyq show notes

super + s
	bspc node -t {floating,tiled}

super + shift + i
    minimizer unhide

super + i
    minimizer hide

alt + shift + {1-9,0}
    bspc node -f @/ ; bspc node -d '^{1-9,10}' --follow

super + {_,shift + }{Left,Down,Up,Right}
	~/.config/bspwm/scripts/move-window {_,edge-}{west,south,north,east}

super + grave
    dunstctl history-pop

super + shift + grave
    dunstctl close

super + u
    ~/.bin/yts -D

super + n
    rrbw
super + m
	WINIT_X11_SCALE_FACTOR=1.1 alacritty  -e ssh salvahe.co
