#!/bin/bash
super + colon
    $HOME/.virtualenvs/yat/bin/python $HOME/Projects/yat/src/gui.py

super + semicolon
    dialect

super + g
    mpv --no-resume-playback --shuffle ~/Videos/Music\ Videos 

super + shift + g
    $HOME/Carousel/scripts/wireguard-vpn -t

ctrl + q
    echo "firefox"

alt + space
    $HOME/.bin/finder

alt + shift + space
    $HOME/.bin/vp-finder resume

super + shift + space
    $HOME/.bin/vp-finder

super + q 
    $HOME/.config/rofi/powermenu/powermenu.sh 

super + space
    $HOME/.config/rofi/launchers/colorful/launcher.sh

super + d
	redpaper -d

super + c
	redpaper -c

super + shift + c
	redpaper -b

super + p
    ~/.bin/cpicker hex

super + shift + p
    ~/.bin/cpicker hsl

super + alt + p
    ~/.bin/cpicker rgb

super + e
    caja

super + shift + Escape
    xkill

#Terminal emulator
super + Return
	WINIT_X11_SCALE_FACTOR=1.2 alacritty

super + t
    WINIT_X11_SCALE_FACTOR=1.2 alacritty -e tomb -q open /polaris/catacomb -k /polaris/skeleton

super + shift + t
	tomb close

super + shift + d
	dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'
    xlayoutdisplay -p eDP1 -o HDMI1 -d 100

super + shift + s
	pkill -f sxhkd && ~/.bin/sxhkdd & disown

ctrl + alt + f
    firefox

ctrl + shift + alt + p
    firefox --private-window

ctrl + alt + o
     ~/.config/bspwm/scripts/compton-toggle.sh

ctrl + alt + Delete
    kill -9 -1

ctrl+Print
	flameshot screen -r -c -p $HOME/Pictures/screenshots

shift + Print
	flameshot gui

#########################
#     MULTIMEDIA KEYS   #
#########################

#Raises volume
XF86AudioRaiseVolume
    pamixer -i 5

#Lowers volume
XF86AudioLowerVolume
    pamixer -d 5

#Mute
XF86AudioMute
    pamixer -t

XF86AudioPlay
    playerctl play-pause

XF86AudioNext
	playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86MonBrightnessUp
    xbacklight -inc 5

XF86MonBrightnessDown
    xbacklight -dec 5

super + r
    ~/.bin/open_in_mpv

super + {_,shift} + bracket{left}
    copyq {menu,show} clipboard
	
super + bracket{right}
    ~/.bin/vsc-open

super + s
	bspc node -t {floating,tiled}

super + m
    pavucontrol &

super + shift m
    ~/.config/bspwm/scripts/toggle-audio-profile

super + grave
    dunstctl history-pop

super + shift + grave
    dunstctl close

super + u
    ~/.bin/yts -D

super + F9
    xrandr --output eDP1 --off

super + shift + F9
    xrandr --output eDP1 --rate 144.00 --mode 1920x1080 --right-of HDMI1

super + F11
    ~/.config/qtile/scripts/xrandr-manager

super + question
    ~/.bin/spellq

super + b
    ~/.bin/configfinder
