#!/bin/sh
#power
#    echo 'power'
super + colon
    $HOME/.virtualenvs/yat/bin/python $HOME/Projects/yat/src/gui.py

super + semicolon
    dialect

super + r
    notify-send "MPV" "Loading content" && mpv $(xclip -o) || notify-send   "Mpv" "Invlid Url"

super + g
    mpv --no-resume-playback --shuffle ~/Videos/Music\ Videos 

super + shift + g
    $HOME/Carousel/scripts/wireguard-vpn -t

ctrl + q
    echo "firefox"

alt + space
    $HOME/.bin/finder

alt + shift + space
    $HOME/.bin/vp-finder resume

super + shift + space
    $HOME/.bin/vp-finder

super + q 
    $HOME/.config/rofi/powermenu/powermenu.sh 

super + Tab
    bspc node -f next.local.\!hidden.window

super + shift + Tab
    bspc node -f prev.local.\!hidden.window

super + shift + y
    polybar-msg cmd toggle

super + y
    $HOME/.config/polybar/launch.sh

super + space
    $HOME/.config/rofi/launchers/colorful/launcher.sh

super + d
	redpaper -d

super + c
	redpaper -c

super + shift + c
	redpaper -b

super + shift + x
	bspc node -k

super + b
	WINIT_X11_SCALE_FACTOR=1.12 alacritty  -e nvim $HOME/.config/bspwm/bspwmrc

super + shift + b
	WINIT_X11_SCALE_FACTOR=1.12 alacritty  -e nvim $HOME/.config/sxhkd/sxhkdrc && pkill -USR1 -x sxhkd && sxhkd

super + w
	bspc node -g {sticky=on, sticky=off}

super + p
    ~/.bin/cpicker hex

super + shift + p
    ~/.bin/cpicker hsl

super + alt + p
    ~/.bin/cpicker rgb

super + e
    caja

super + f
	bspc node --state \~fullscreen


super + shift + Escape
    xkill

#Terminal emulator
super + Return
	WINIT_X11_SCALE_FACTOR=1.2 alacritty

super + t
    WINIT_X11_SCALE_FACTOR=1.2 alacritty -e tomb -q open $HOME/Desktop/lollypop -k $HOME/Desktop/popen

super + shift + t
	tomb close

super + shift + d
	dmenu_run -i -nb '#191919' -nf '#fea63c' -sb '#fea63c' -sf '#191919' -fn 'NotoMonoRegular:bold:pixelsize=14'
    xlayoutdisplay -p eDP1 -o HDMI1 -d 100

super + F5
    	~/.config/bspwm/scripts/switch-displays

super + shift + s
	pkill -x sxhkd && sxhkd

super + shift + q
	bspc node -c

super + shift + x
    bspc quit


#########################
# CONTROL + ALT KEYS    #
#########################


#firefox
ctrl + alt + f
    firefox

ctrl + shift + alt + p
    firefox --private-window

#Compton Toggle
ctrl + alt + o
     ~/.config/bspwm/scripts/compton-toggle.sh

ctrl + alt + Delete
    kill -9 -1


#########################
#     SCREENSHOTS       #
#########################

ctrl+Print
	flameshot screen -r -c -p $HOME/Pictures/screenshots

shift + Print
	flameshot gui

#########################
#     MULTIMEDIA KEYS   #
#########################

#Raises volume
XF86AudioRaiseVolume
    pamixer -i 5

#Lowers volume
XF86AudioLowerVolume
    pamixer -d 5

#Mute
XF86AudioMute
	[ $(pamixer --get-mute) = "true" ] && pamixer -u || pamixer -m


XF86AudioPlay
    playerctl play-pause

XF86AudioNext
	playerctl next

XF86AudioPrev
    playerctl previous

XF86AudioStop
    playerctl stop

XF86MonBrightnessUp
    xbacklight -inc 5

XF86MonBrightnessDown
    xbacklight -dec 5


super + {1-9,0}
	bspc desktop -f '^{1-9,10}'

super + shift + {1-9,0}
    id=$(bspc query -N -n); bspc node -d ^{1-9,10}; bspc node -f ${id}

super + v
    ~/.config/bspwm/scripts/minimizer layout

super + {h,j,k,l}
    bspc node --focus {west,south,north,east}
    
super + shift + {h,j,k,l} 
    { dir=west \
    , dir=south \
    , dir=north \
    , dir=east  \
    }; \
    if bspc query -n $dir.window -N; then \
        bspc node --swap $dir --focus;\
    else \
        bspc node -m $dir --focus;\
    fi

super + {_,shift + }a
	bspc node @/ --flip {vertical,horizontal}

super + {Left,Down,Up,Right}
	bspc node -z {left -20 0,bottom 0 20,top 0 -20,right 20 0}

super + shift + {Left,Down,Up,Right}
	bspc node -z {right -20 0,top 0 20,bottom 0 -20,left 20 0}


super + {_,shift} + o
    bspc node @/ --rotate {90, 270}

super + r
    ~/.bin/open_in_mpv

super + {_,shift} + bracket{left}
    copyq {menu,show} clipboard
	
super + bracket{right}
    ~/.bin/vsc-open
    

super + s
	bspc node -t {floating,tiled}
super + m
    ~/.config/bspwm/scripts/toggle-audio-profile
super + shift + m
    pavucontrol &
super + shift + i
    ~/.config/bspwm/scripts/minimizer unhide

super + i
    ~/.config/bspwm/scripts/minimizer hide

super + {_,shift + }{Left,Down,Up,Right}
	~/.config/bspwm/scripts/move-window {_,edge-}{west,south,north,east}

super + grave
    dunstctl history-pop

super + shift + grave
    dunstctl close

super + u
    ~/.bin/yts -D

super + F9
    xrandr --output eDP1 --off
super + {shift + } + F9
    xrandr --output eDP1 --rate 144.00 --right-of HDMI1 --rate 144.00
super + F4
    clockify
