#!/usr/bin/env python

from os import walk, getcwd
from os.path import join, exists
import os
import shutil
import sys

start = getcwd()


def mover():
    for root, dirs, files in walk(start):
        dirpaths = [join(root, dir) for dir in dirs]
        dirbelow3 = []
        for path in dirpaths:
            if len(os.listdir(path)) < 3:
                dirbelow3.append(path)
        for p in dirbelow3:
            f = os.listdir(p)
            try:
                os.rename(join(p, f[0]), join(singles, f[0]))
                print(f"{join(p, f[0])} >>> {join(singles, f[0])}")
                os.rename(join(p, f[1]), join(singles, f[1]))
                print(f"{join(p, f[1])} >>> {join(singles, f[1])}")
            except IndexError:
                continue
            except FileExistsError:
                continue

try:
    singles = join(start, "singles")
    mover()
except FileNotFoundError:
    os.mkdir(join(start, "singles"))
    singles = join(start, "singles")
    mover()