#!/bin/python

import os
import subprocess
import sys
from dataclasses import dataclass

HOME = os.path.expanduser("~")

sink_cmd = subprocess.run(["pactl", "list", "sinks"], check=True, capture_output=True)
sinks_props_string = (
    subprocess.run(
        ["grep", "State:", "-A", "2"], input=sink_cmd.stdout, capture_output=True
    )
    .stdout.decode("utf-8")
    .strip()
    .split("--")
)

current_name = (
    subprocess.run(["pactl", "get-default-sink"], capture_output=True)
    .stdout.decode()
    .strip()
)


@dataclass
class Sink:
    state: str = ""
    name: str = ""
    description: str = ""

    def __str__(self) -> str:
        return f"name: {self.name}, desc: {self.description}, state: {self.state}"


current_default: str = ""

sinks: dict[str, Sink] = dict()
for sink_str in sinks_props_string:
    sink = Sink()
    if "easyeffects" in sink_str:
        continue
    props = sink_str.replace("\t", "").strip().split("\n")
    for prop in props:
        key, val = prop.split(": ")
        setattr(sink, key.lower(), val)
    sinks[sink.description] = sink
    if sink.name == current_name:
        current_default = sink.description


sink_count = len(sinks)
for sink in sinks:
    print(sink)
if sink_count == 1:
    print("only one sink", sinks)
    sys.exit()

if sink_count == 2:
    print("toggling between sinks")
    next_sink = [s for s in sinks.values() if s.name != current_name][0]
    subprocess.run(["pactl", "set-default-sink", next_sink.name])
    subprocess.run(["notify-send", "-i", "speaker", "Audio", next_sink.description])
    sys.exit()


sink_names = "\n".join([s for s in sinks if s != current_default])
fuzz = (
    subprocess.run(
        [
            "fuzzel",
            "--dmenu",
            "--config",
            os.path.join(HOME, ".bin/prompt-theme.ini"),
            "-p",
            "Device:",
            "-l",
            str(len(sinks)),
            "-i",
            # "--no-exit-on-keyboard-focus-loss",
        ],
        input=sink_names.encode(),
        capture_output=True,
    )
    .stdout.decode()
    .strip()
)
if not fuzz:
    sys.exit()
subprocess.run(["pactl", "set-default-sink", sinks[fuzz].name])
subprocess.run(["notify-send", "-i", "speaker", "Audio", fuzz])
