#!/bin/bash

SERVER_EXPORT='10.0.0.2:/store/media'
MOUNT_TARGET='/media'

# Nothing to do if user does not have requisite binaries.
[[ -z $(which ping) ]] && echo 'Install iputils or whatever package provides ping' && exit 0
[[ -z $(which mountpoint) ]] && echo 'Install util-linux or whatever package provides mountpoint' && exit 0

mountpoint -q $MOUNT_TARGET || sudo mount -t nfs4 $SERVER_EXPORT $MOUNT_TARGET
