#!/bin/zsh
HIST_FILE=~/.cache/finders/configfinder
RG="$(rg --files ~/dotfiles -. --ignore-file ~/dotfiles/.gitignore --ignore-file ~/.bin/ignore)"
HIST="$(head -n9 $HIST_FILE)"
FUZZ="$(echo $HIST $RG | dmenu -i -l 10  -p File: -nb '#1E1C31' -nf '#ccc' -sb '#E5C07B' -sf '#1E1C31')"
if [[ -f $FUZZ ]]
then 
  echo "$HIST" | grep -vF "$FUZZ" | sed "1i$FUZZ" > $HIST_FILE
  kitty -e nvim "$FUZZ"
fi
