#!/bin/sh
# colorpicker --preview  --short --one-shot | xclip -selection clipboard
while getopts hr flag
do
case "${flag}" in
    h) 
    colorpicker  --short --one-shot | tr -d "\n","#" | xclip -selection clipboard ;;
    r)
    colorpicker --one-shot | awk '{print $2$4$6}'i |tr -d "\n" | xclip -selection clipboard ;;
esac 
done

