#!/bin/zsh
#
# This script looks for media stored in a custom NAS. The actual media paths are /media
rg="$($HOME/.bin/fs /media/music /media/videos/music/ -i services,/media/downloads --host '10.0.0.10:6450')"
if [[ "$XDG_SESSION_TYPE" == "wayland" ]];then
    fuzz="$(print $rg | fuzzel --dmenu \
        -b '1e1e2eff' -t 'cdd6f4ff' -s 'f9e2afff' -S '313244ff'\
        -f 'Fira Mono Nerd Font:size=9'\
        -p 'File: '\
        -w 150 \
        -r 0 -C 'f9e2afff' -B 2 \
        -i \
        --no-exit-on-keyboard-focus-loss \
        )"
else
    fuzz="$(echo $hist $rg | dmenu -i -l 10  -p file: -nb '#1e1c31' -nf '#ccc' -sb '#e5c07b' -sf '#1e1c31')"
fi
echo "$fuzz"

# _fuzz=$(echo $fuzz|sed 's*/store/*/*')
# echo $_fuzz

if [ ! -z $fuzz ] && [ -f $fuzz ]
then 
  echo "$hist" | grep -vF $fuzz | sed "1i$fuzz" > $hist_file
  xdg-open $fuzz & disown
else
    echo "Not a file"
fi
