#!/bin/bash
while getopts d:t:n: flag
do
case "${flag}" in
d) d=${OPTARG}
    delay=$d;;
t) t=${OPTARG}
    hour=$(date --date="$t" "+%H")
    current_hour=$(date "+%H")
    current_time=$(date "+%s")
    ((hour < current_hour)) && 
	delay=$(($(date --date="$t 1 day" "+%s") - $current_time)) ||
	delay=$(($(date --date="$t" "+%s") - $current_time));;
n) note=${OPTARG};;
*) echo 'unknown flag' && return 1
esac 
done
(sleep $delay && notify-send "$note" &&
mpv --force-window=no /usr/share/sounds/freedesktop/stereo/service-login.oga) &> /dev/null & disown
