#!/usr/bin/env bash

# A script to search for youtube videos and open them in mpv

if [[ -z "$1" ]]; then
  printf "Search query: "; 
  query=$(echo "" | rofi -dmenu  -p "Search YT Video:")   
else
	query="$1"
fi

if [[ ! -z "$query" ]]; then
    query="${query// /+}"
    echo "$query"

    # YT_API_KEY location
    YT_API_KEY="$( cat "${HOME}"/.api-keys/yt-api-key )"
    urlstring="https://www.googleapis.com/youtube/v3/search?part=snippet&q=${query}&type=video&maxResults=20&key=${YT_API_KEY}"

    mpv --no-resume-playback  "https://$( curl -s "${urlstring}" \
        | jq -r '.items[] | "\(.snippet.channelTitle) => \(.snippet.title) => youtu.be/\(.id.videoId)"' \
        | rofi -dmenu -no-disable-history -theme-str '#window { width: 70%; height: 50%; } #listview { columns: 1;}' -i -p 'Select Video -' -l 20 \
        | awk '{print $NF}' \
    )"
else
    exit
fi
