--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ted/Pictures/Redpaper/Astronaut and the black hole fantasy space [1920x1080].jpeg"

-- Special
background="#120819"
foreground="#afc2d5"
cursor="#afc2d5"

-- Colors
color0="#120819"
color1="#34358C"
color2="#4F368F"
color3="#334E9D"
color4="#5E55A3"
color5="#9766AA"
color6="#C165A6"
color7="#afc2d5"
color8="#7a8795"
color9="#34358C"
color10="#4F368F"
color11="#334E9D"
color12="#5E55A3"
color13="#9766AA"
color14="#C165A6"
color15="#afc2d5"
