# Shell variables
# Generated by 'wal'
wallpaper='/home/ted/Pictures/Redpaper/Astronaut and the black hole fantasy space [1920x1080].jpeg'

# Special
background='#120819'
foreground='#afc2d5'
cursor='#afc2d5'

# Colors
color0='#120819'
color1='#34358C'
color2='#4F368F'
color3='#334E9D'
color4='#5E55A3'
color5='#9766AA'
color6='#C165A6'
color7='#afc2d5'
color8='#7a8795'
color9='#34358C'
color10='#4F368F'
color11='#334E9D'
color12='#5E55A3'
color13='#9766AA'
color14='#C165A6'
color15='#afc2d5'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
