# Shell variables
# Generated by 'wal'
wallpaper='/home/ted/Pictures/Redpaper/Firewatch but without man-made objects or birds..png'

# Special
background='#1c0a1b'
foreground='#f6e4d9'
cursor='#f6e4d9'

# Colors
color0='#1c0a1b'
color1='#CA2B41'
color2='#EC5744'
color3='#FE7445'
color4='#FE8351'
color5='#BE7386'
color6='#FCBCA3'
color7='#f6e4d9'
color8='#ac9f97'
color9='#CA2B41'
color10='#EC5744'
color11='#FE7445'
color12='#FE8351'
color13='#BE7386'
color14='#FCBCA3'
color15='#f6e4d9'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
