--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ted/Pictures/Redpaper/My favorite of my series, each with a different theme and color. Hi-Res Available. [OC] [1920x1080].png"

-- Special
background="#1c030d"
foreground="#f5e9e0"
cursor="#f5e9e0"

-- Colors
color0="#1c030d"
color1="#DE6E4A"
color2="#D28452"
color3="#F1945E"
color4="#D77C8B"
color5="#DEB59B"
color6="#FBDDC8"
color7="#f5e9e0"
color8="#aba39c"
color9="#DE6E4A"
color10="#D28452"
color11="#F1945E"
color12="#D77C8B"
color13="#DEB59B"
color14="#FBDDC8"
color15="#f5e9e0"
