# Shell variables
# Generated by 'wal'
wallpaper='/home/ted/Pictures/Redpaper/Skyscrapers [2560x1440].jpeg'

# Special
background='#0c0816'
foreground='#8fc5c6'
cursor='#8fc5c6'

# Colors
color0='#0c0816'
color1='#9E2A5E'
color2='#D03C6E'
color3='#9D596B'
color4='#378B77'
color5='#346D8A'
color6='#CD6A8C'
color7='#8fc5c6'
color8='#64898a'
color9='#9E2A5E'
color10='#D03C6E'
color11='#9D596B'
color12='#378B77'
color13='#346D8A'
color14='#CD6A8C'
color15='#8fc5c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
