--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/ted/Pictures/Redpaper/Firewatch but without man-made objects or birds..png"

-- Special
background="#1c0a1b"
foreground="#f6e4d9"
cursor="#f6e4d9"

-- Colors
color0="#1c0a1b"
color1="#CA2B41"
color2="#EC5744"
color3="#FE7445"
color4="#FE8351"
color5="#BE7386"
color6="#FCBCA3"
color7="#f6e4d9"
color8="#ac9f97"
color9="#CA2B41"
color10="#EC5744"
color11="#FE7445"
color12="#FE8351"
color13="#BE7386"
color14="#FCBCA3"
color15="#f6e4d9"
