#!/bin/bash
mem_used=$(cat /sys/class/hwmon/hwmon2/device/mem_info_vram_used)
mem_total=$(cat /sys/class/hwmon/hwmon2/device/mem_info_vram_total)
gpu_busy=$(cat /sys/class/hwmon/hwmon2/device/gpu_busy_percent)

mem_usage=$(bc <<< "scale=2; $mem_used / 1048576")

if [ "$1" = "m" ]; then
    mem_usage=$(bc <<< "scale=2; $mem_used / 1073741824")
    printf "%s%% | %.2fGB" "$gpu_busy" "$mem_usage"
else
    mem_usage=$(bc <<< "scale=2; ($mem_used * 100) / $mem_total")
    printf "%s%% | %.2f%%" "$gpu_busy" "$mem_usage"
fi


