#!/bin/bash 
if ip a | grep 'tun' -q;then
    printf " $(ps -p $(pgrep -f openvpn) -o cmd --no-headers | cut -d' ' -f3 | rev | cut -d'/' -f1 | rev | cut -d'.' -f1 | tr '[:lower:]' '[:upper:]')"
else
    printf ""
fi

