#!/bin/sh
output="alsa_output.pci-0000_00_1f.3"
card="alsa_card.pci-0000_00_1f.3"
hdmi_sink="$output.hdmi-stereo"
analog_sink="$output.analog-stereo"
hdmi_out_analog_in="output:hdmi-stereo+input:analog-stereo"
analog_out_analog_in="output:analog-stereo+input:analog-stereo"
if [[ $(pactl get-default-sink) == $hdmi_sink ]]
then pactl set-card-profile $card $analog_out_analog_in
  echo $card $analog_out_analog_in
else pactl set-card-profile $card $hdmi_out_analog_in
  echo $card $hdmi_out_analog_in
fi


